---
services:
  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
    volumes:
      - /data/kafka/logs:/tmp/kraft-combined-logs
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://192.168.21.96:9092,PLAINTEXT://broker:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://broker:9092"]
      interval: 30s
      timeout: 10s
      retries: 50

  syslog-ng:
    image: balabit/syslog-ng:latest
    hostname: syslog-ng
    ports: 
      - '514:514/udp'
      - '601:601'
    volumes:
      - type: bind
        source: "$PWD/syslog-ng.conf"
        target: "/etc/syslog-ng/syslog-ng.conf"
    depends_on:
      - broker

  jupyterlab:
    container_name: jupyter-datascience
    image: quay.io/jupyter/datascience-notebook:latest
    restart: always
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - '8888:8888'
      
  template-parser:
    container_name: mon-template-parser
    image: paas-python:1
    volumes:
      - ../kafka-components/1-template-parser/:/app
    environment:
      TEMPLATE_PARSER_KAFKA_LOG_ORCHESTRATOR_TOPIC: test
      TEMPLATE_PARSER_KAFKA_VAL_TEMPL_TOPIC: validated_templates 
      TEMPLATE_PARSER_KAFKA_LOG_APP_TOPIC: log-orchestrator-logs 
      TEMPLATE_PARSER_KAFKA_BOOTSTRAP_SERVERS: 192.168.21.96:9092 
    command: python3 /app/1_template_parser.py
